services:
    app.file.post_handler:
        class: AppBundle\Form\Handler\FilePostHandler
        arguments:
            - %allowed_applications%
            - '@app.assets.manager'
            - '%%kernel.cache_dir%'

    app.assets.manager:
        class: AppBundle\Assets\AssetsManager
        arguments:
            - %resources_path%
